name: Generate Graphs

on:
  schedule:
    - cron: '0 6-21 * * *'  # Runs at the beginning of every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Generate chart
      run: python code/generate_graphs.py
      
    - name: Commit and push chart
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add graphs/
        git commit -m "Update chart for $(date -u '+%Y-%m-%d %H')" || echo "No changes to commit"
        git push